### ISSUE TITLE
FEATURE REQ: Auto-subscribe to Healthcare Authorities

### ISSUE THREAD

**Issue by penrods** [tripleblindmarket/covid-safe-paths#425]
Currently the user must manually subscribe to a Healthcare Authority.  This will grow to a point where it is a difficult UI to work with.  I propose the following:

1) Extend the Healthcare Authority yaml which lives on the safe-places repo to include a GPS bounding box.
2) If the user has no existing Healthcare Authority, the app checks that file once every 24 hours.  If the user's current GPS coordinate is within any bounding box, they should be given a popup notification that a Healthcare Authority exists in their are, "Would you like to subscribe?"
** This should only happen until they have the first authority to avoid overloading the server with millions of requests **
3) A similar process can be used when the user manually enters the Subscription page.  I'm not worried about server overload on a manual process.  This can limit the list to authorities which contain any of the points in their full 28-day GPS history, then have a checkbox that will show All Authorities.

The list which they are checked against should be a "production" URL from http://raw.githack.com/.  This will provide decent buffering of the Github server infrastructure, but it is VERY IMPORTANT we purge the cache anytime a new Healthcare Authority is added to the YAML.

This is the production (cached for a year) CDN URL:
https://rawcdn.githack.com/tripleblindmarket/safe-places/940edc081b8a4771deca806ed570eda907b5a261/healthcare-authorities.yaml

**Comment by tstirrat** [comment]
@Patrick-Erichsen was looking into this, I think

**Comment by Patrick-Erichsen** [comment]
I believe #375  is the same body of work. But this explanation is much more in-depth, so we could close #375 in favor of this.

**Comment by Patrick-Erichsen** [comment]
@penrods  Is there any proposed schema for what the HCA YAML file might look like? The current one does not include the GPS bounding box required to complete this issue.

**Comment by Patrick-Erichsen** [comment]
@penrods @tstirrat any updates on a proposed schema for the GPS bounding box of a Healthcare Authority?

 I'm planning on implementing an `isPointInRegion()` function that can be used to check if a user's GPS history has any points that are within the bounding box of an HCA, but without the schema for that bounding box, I can't get started.

**Comment by DenisPitcher** [comment]
How would someone actually update the healthcare-authorities.yaml file to add an authority?

**Comment by tremblerz** [comment]
Do you think we should just generate Geohashes on both sides?

**Comment by penrods** [comment]
@tremblerz, this is really a bounding box so keeping it in distinct lat/lon is useful.  Pseudo-code is:
```
inside = lat < latMax && lat > latMin && lon < lonMax && lon > lonMin
```

I'm proposing the following YAML format:
```yaml
Authorities:
- Mairie de PAP/MSSP:
  - {url: "https://vault.tripleblind.app/safe_path/5673742378205184/"} 
  - bounds: { "ne": { "lat": 42.42025904738132, "lon": -70.93670068664551 }, "sw": { "lat":42.29988330010084, "lon": -71.2516993133545} }
```

I don't love the length of the "bounds" line, but that is easily copy/pasted, as opposed to:

```yaml
Authorities:
- Mairie de PAP/MSSP:
  - {url: "https://vault.tripleblind.app/safe_path/5673742378205184/"} 
  - bounds: 
     ne: { "lat": 42.42025904738132, "lon": -70.93670068664551 }
     sw: { "lat":42.29988330010084, "lon": -71.2516993133545}
```
Which has the same structure, just formatted differently visually.

**Comment by Patrick-Erichsen** [comment]
I think that the bounds are essentially just a single piece of info as well, so it makes sense to keep it as a single field. It would be weird to break out the URL above into something like 
```yaml
protocol: ...
hostname: ... 
resource: ...
```
